### ISSUE TITLE
Release for Firefox

### ISSUE THREAD

**Issue by jvllmr** [coderesting/NAKExtension#19]
At least the autoLogin feature works with no edits on Firefox -> Release for Firefox / Release with limited features (if some don't work) ?
Haven't tested any other feature in Firefox yet.

**Comment by coderesting** [comment]
Thanks for the hint. I made the extension ready for Firefox and sent a submission to https://addons.mozilla.org/.
I'll keep you updated on the progress.

Yannick

**Comment by coderesting** [comment]
The extension is now available as a [Firefox Add-On](https://addons.mozilla.org/en-US/firefox/addon/nak-extension/).
