### ISSUE TITLE
Add possibility to receive Mobile Notifications

### ISSUE THREAD

**Issue by IceToast** [coderesting/NAKExtension#25]
I've had an idea: Mobile Notification. Well we had this idea a long time ago but we decided not to implement this as it would lead to have every user registered to a no free 3rd party service.

I got my hands on a project which solves this "problem" and provides a self hosted notification service.

My idea on this is:
- Every user can self host their own notification service using [Gotify](https://gotify.net/)
- Every other user can use a hosted service by me :)

**Comment by coderesting** [comment]
Can you explain in more detail what problem this addition would solve?

**Comment by IceToast** [comment]
For me personally the desktop notifications are working fine. But there were times when i afk i got a notification. I've not seen it until the next day ^^

Other students asked me to reevaluate the mobile notification feature, as we decided not to implement it.

I have to mention:
This will only work for Android... It seems there is no free service for iOS

**Comment by IceToast** [comment]
I want to mention, that this feature is pretty easy to code and does not need more research as it is already done.

**Comment by coderesting** [comment]
Well, if the feature is not too complicated feel free to create a PR 🙂

**Comment by IceToast** [comment]
Well nvm. Its easy possible to support this for android, since Gotify does support Android and thus has an Android App :D 
But there is nothing like this for iOS. Thats why i decided not to implement this ^^
