### ISSUE TITLE
Auto login for Shibboleth

### ISSUE THREAD

**Issue by coderesting** [coderesting/NAKExtension#26]
Auto login on the URL https://idp.nordakademie.de/idp/profile/SAML2/* would allow users to be logged into all of the Shibboleth websites like Springer-Link.

**Comment by jnnsrctr** [comment]
Is there any way to also fill out the form where the university has to be chosen?
https://wayf.springernature.com/?redirect_uri=https://link.springer.com

**Comment by coderesting** [comment]
Hi @jnnsrctr,
sounds pretty possible :)
I try to work on it asap.

Have a nice day,
Yannick

**Comment by coderesting** [comment]
Implemented in version 1.3.0 (currently waiting for Chrome and Firefox approval).
Should be live in a few days.
