### ISSUE TITLE
Auto login for Barracuda Email Security Gateway

### ISSUE THREAD

**Issue by jnnsrctr** [coderesting/NAKExtension#29]
The NAK Spam filter uses the same login as the CIS. Could be automated
[https://merkur.nordakademie.de/](https://merkur.nordakademie.de/)

**Comment by coderesting** [comment]
Hi @johannes-ri,
nice recommendation 👍. I added it in 4b4ac9f37287701fa90fd43460aee7c48ca3512a.
Since there is another [feature](https://github.com/coderesting/NAKTools/issues/4) for the extension I'd like to finish that one too and than release both together in the next version.

Cheers
Yannick

**Comment by coderesting** [comment]
Implemented in version 1.3.0 (currently waiting for Chrome and Firefox approval).
Should be live in a few days.
